### ISSUE TITLE
all_test: compilation failure with go 1.11

### ISSUE THREAD

**Issue by decathorpe** [cznic/mathutil#11]
```
$GOPATH/src/github.com/cznic/mathutil/all_test.go:4466: dbg call has arguments but no formatting directives
```

**Comment by cznic** [comment]
Seems like this refers to some outdated version: see https://github.com/cznic/mathutil/blob/ca4c9f2c136954238c3158b92de72078c7672ecc/all_test.go#L4466.

Please confirm, thanks.

**Comment by decathorpe** [comment]
Argh. You are right, of course.

I thought I had checked that I was using an up-to-date commit, but it turns out that I didn't do that after all.

Sorry for the false alarm.
