### ISSUE TITLE
FAIL: TestFactorInt 

### ISSUE THREAD

**Issue by jhoonb** [cznic/mathutil#4]
Hello,
running in (Windows 7 - 32bit): go test

return:

--- FAIL: TestFactorInt (0.44s)
	all_test.go:814: bad FactorInt(4294967295): [{4294967295 1}]
FAIL
exit status 1
FAIL	github.com/cznic/mathutil	142.642s

but, Ubuntu 15.04 64bit work :)

what's wrong?

**Comment by cznic** [comment]
Works here as well with 64b Linux. Now downloading a 32b distro to try in a VM. I have no access to any Windows machine ATM.

**Comment by cznic** [comment]
Thank you very much for the report. Fix follows.

**Comment by jhoonb** [comment]
thank you!!
