### ISSUE TITLE
FAIL: TestQuadPolyFactors (overflow on 32 bit architectures)

### ISSUE THREAD

**Issue by decathorpe** [cznic/mathutil#6]
I'm trying to create a proper package of this library for fedora, and the tests work fine on 64-bit architectures, but I get this overflow error on i386 and armv7hl:

on i386:
```
+ go test -compiler gc -ldflags '' github.com/cznic/mathutil
--- FAIL: TestQuadPolyFactors (0.00s)
	all_test.go:3630: 0: 7433(3155x+5915)(8168x+2313) = -1724821000x^2+1041449339x-1385406069 -> overflow
FAIL
FAIL	github.com/cznic/mathutil	119.487s
```

on armv7hl:
```
+ go test -compiler gc -ldflags '' github.com/cznic/mathutil
--- FAIL: TestQuadPolyFactors (0.00s)
	all_test.go:3630: 0: 7433(3155x+5915)(8168x+2313) = -1724821000x^2+1041449339x-1385406069 -> overflow
FAIL
FAIL	github.com/cznic/mathutil	594.629s
```

**Comment by cznic** [comment]
@decathorpe Thanks for the report. Please test and feel free to reopen if it's still broken, I don't have a 32-bit system around ATM. Thank you.

**Comment by decathorpe** [comment]
Wow, that was fast. Works fine on i386 and armv7hl (after increasing the test timeout from the default 10m to 30m) now. Thanks!
